name: "Pipeline gerção de imagem docker Bandas"
on: 
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: "02"
  
jobs:
  verificacao-dos-codigos:
    name: "Validacao dos Codigos"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout do repositorio"
        uses: actions/checkout@v4

      - name: Mostrar estrutura workflows
        run: | 
            echo "Estrutura do workflow"
            ls -la .github/workflows
            echo ""
            echo "Total de Worflows: $(ls -la .github/workflows | wc -l)" 
      
      - name: "Elementos Obrigatorios do workflow"
        run: |
            echo "Elementos obrigatorios do workflow"
            echo "Nome do workflow: ${{ github.workflow }}"
            echo "Evento que disparou o workflow: ${{ github.event_name }}"
            echo "Branch que disparou o workflow: ${{ github.ref }}"
            echo "Repositorio que disparou o workflow: ${{ github.repository }}"
       
      - name: "Variaveis e contexto"
        run: |
            echo "Variaveis e contexto do workflow ${{env.NODE_VERSION}}"
            echo "Nome do workflow: ${{ github.workflow }}"
            echo "Evento que disparou o workflow: ${{ github.event_name }}"
            echo "Branch que disparou o workflow: ${{ github.ref }}"
            echo "Repositorio que disparou o workflow: ${{ github.repository }}"        